// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MutualExclusionClient is the client API for MutualExclusion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MutualExclusionClient interface {
	// Sends a greeting for a new participant
	NewParticipant(ctx context.Context, in *NewClientRequest, opts ...grpc.CallOption) (*NewClientReply, error)
	//Client wants to manipulate
	ClientManipulation(ctx context.Context, in *ClientManipulationRequest, opts ...grpc.CallOption) (*ClientManipulationReply, error)
}

type mutualExclusionClient struct {
	cc grpc.ClientConnInterface
}

func NewMutualExclusionClient(cc grpc.ClientConnInterface) MutualExclusionClient {
	return &mutualExclusionClient{cc}
}

func (c *mutualExclusionClient) NewParticipant(ctx context.Context, in *NewClientRequest, opts ...grpc.CallOption) (*NewClientReply, error) {
	out := new(NewClientReply)
	err := c.cc.Invoke(ctx, "/communication.MutualExclusion/NewParticipant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mutualExclusionClient) ClientManipulation(ctx context.Context, in *ClientManipulationRequest, opts ...grpc.CallOption) (*ClientManipulationReply, error) {
	out := new(ClientManipulationReply)
	err := c.cc.Invoke(ctx, "/communication.MutualExclusion/ClientManipulation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MutualExclusionServer is the server API for MutualExclusion service.
// All implementations must embed UnimplementedMutualExclusionServer
// for forward compatibility
type MutualExclusionServer interface {
	// Sends a greeting for a new participant
	NewParticipant(context.Context, *NewClientRequest) (*NewClientReply, error)
	//Client wants to manipulate
	ClientManipulation(context.Context, *ClientManipulationRequest) (*ClientManipulationReply, error)
	mustEmbedUnimplementedMutualExclusionServer()
}

// UnimplementedMutualExclusionServer must be embedded to have forward compatible implementations.
type UnimplementedMutualExclusionServer struct {
}

func (UnimplementedMutualExclusionServer) NewParticipant(context.Context, *NewClientRequest) (*NewClientReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewParticipant not implemented")
}
func (UnimplementedMutualExclusionServer) ClientManipulation(context.Context, *ClientManipulationRequest) (*ClientManipulationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientManipulation not implemented")
}
func (UnimplementedMutualExclusionServer) mustEmbedUnimplementedMutualExclusionServer() {}

// UnsafeMutualExclusionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MutualExclusionServer will
// result in compilation errors.
type UnsafeMutualExclusionServer interface {
	mustEmbedUnimplementedMutualExclusionServer()
}

func RegisterMutualExclusionServer(s grpc.ServiceRegistrar, srv MutualExclusionServer) {
	s.RegisterService(&MutualExclusion_ServiceDesc, srv)
}

func _MutualExclusion_NewParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutualExclusionServer).NewParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.MutualExclusion/NewParticipant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutualExclusionServer).NewParticipant(ctx, req.(*NewClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MutualExclusion_ClientManipulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientManipulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutualExclusionServer).ClientManipulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.MutualExclusion/ClientManipulation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutualExclusionServer).ClientManipulation(ctx, req.(*ClientManipulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MutualExclusion_ServiceDesc is the grpc.ServiceDesc for MutualExclusion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MutualExclusion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "communication.MutualExclusion",
	HandlerType: (*MutualExclusionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewParticipant",
			Handler:    _MutualExclusion_NewParticipant_Handler,
		},
		{
			MethodName: "ClientManipulation",
			Handler:    _MutualExclusion_ClientManipulation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "MutualExclusion/protobuf/communication.proto",
}
