// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: MutualExclusion/protobuf/communication.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the client's name.
type NewClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientName string `protobuf:"bytes,1,opt,name=ClientName,proto3" json:"ClientName,omitempty"`
}

func (x *NewClientRequest) Reset() {
	*x = NewClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MutualExclusion_protobuf_communication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewClientRequest) ProtoMessage() {}

func (x *NewClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MutualExclusion_protobuf_communication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewClientRequest.ProtoReflect.Descriptor instead.
func (*NewClientRequest) Descriptor() ([]byte, []int) {
	return file_MutualExclusion_protobuf_communication_proto_rawDescGZIP(), []int{0}
}

func (x *NewClientRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

// The response message containing if the addition was succesful
type NewClientReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewClientReply) Reset() {
	*x = NewClientReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MutualExclusion_protobuf_communication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewClientReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewClientReply) ProtoMessage() {}

func (x *NewClientReply) ProtoReflect() protoreflect.Message {
	mi := &file_MutualExclusion_protobuf_communication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewClientReply.ProtoReflect.Descriptor instead.
func (*NewClientReply) Descriptor() ([]byte, []int) {
	return file_MutualExclusion_protobuf_communication_proto_rawDescGZIP(), []int{1}
}

type ClientManipulationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientName string `protobuf:"bytes,1,opt,name=ClientName,proto3" json:"ClientName,omitempty"`
}

func (x *ClientManipulationRequest) Reset() {
	*x = ClientManipulationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MutualExclusion_protobuf_communication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientManipulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientManipulationRequest) ProtoMessage() {}

func (x *ClientManipulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MutualExclusion_protobuf_communication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientManipulationRequest.ProtoReflect.Descriptor instead.
func (*ClientManipulationRequest) Descriptor() ([]byte, []int) {
	return file_MutualExclusion_protobuf_communication_proto_rawDescGZIP(), []int{2}
}

func (x *ClientManipulationRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

type ClientManipulationReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientManipulationReply) Reset() {
	*x = ClientManipulationReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MutualExclusion_protobuf_communication_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientManipulationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientManipulationReply) ProtoMessage() {}

func (x *ClientManipulationReply) ProtoReflect() protoreflect.Message {
	mi := &file_MutualExclusion_protobuf_communication_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientManipulationReply.ProtoReflect.Descriptor instead.
func (*ClientManipulationReply) Descriptor() ([]byte, []int) {
	return file_MutualExclusion_protobuf_communication_proto_rawDescGZIP(), []int{3}
}

var File_MutualExclusion_protobuf_communication_proto protoreflect.FileDescriptor

var file_MutualExclusion_protobuf_communication_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x4d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f,
	0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x32, 0x0a,
	0x10, 0x4e, 0x65, 0x77, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x10, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x3b, 0x0a, 0x19, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e,
	0x69, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x19, 0x0a, 0x17, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x70, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xcf, 0x01, 0x0a, 0x0f,
	0x4d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x52, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e,
	0x74, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e,
	0x69, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4d, 0x61, 0x6e, 0x69, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x70, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x36, 0x5a,
	0x34, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x61, 0x63, 0x6f, 0x62, 0x4d, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f,
	0x6d, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MutualExclusion_protobuf_communication_proto_rawDescOnce sync.Once
	file_MutualExclusion_protobuf_communication_proto_rawDescData = file_MutualExclusion_protobuf_communication_proto_rawDesc
)

func file_MutualExclusion_protobuf_communication_proto_rawDescGZIP() []byte {
	file_MutualExclusion_protobuf_communication_proto_rawDescOnce.Do(func() {
		file_MutualExclusion_protobuf_communication_proto_rawDescData = protoimpl.X.CompressGZIP(file_MutualExclusion_protobuf_communication_proto_rawDescData)
	})
	return file_MutualExclusion_protobuf_communication_proto_rawDescData
}

var file_MutualExclusion_protobuf_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_MutualExclusion_protobuf_communication_proto_goTypes = []interface{}{
	(*NewClientRequest)(nil),          // 0: communication.NewClientRequest
	(*NewClientReply)(nil),            // 1: communication.NewClientReply
	(*ClientManipulationRequest)(nil), // 2: communication.ClientManipulationRequest
	(*ClientManipulationReply)(nil),   // 3: communication.ClientManipulationReply
}
var file_MutualExclusion_protobuf_communication_proto_depIdxs = []int32{
	0, // 0: communication.MutualExclusion.NewParticipant:input_type -> communication.NewClientRequest
	2, // 1: communication.MutualExclusion.ClientManipulation:input_type -> communication.ClientManipulationRequest
	1, // 2: communication.MutualExclusion.NewParticipant:output_type -> communication.NewClientReply
	3, // 3: communication.MutualExclusion.ClientManipulation:output_type -> communication.ClientManipulationReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MutualExclusion_protobuf_communication_proto_init() }
func file_MutualExclusion_protobuf_communication_proto_init() {
	if File_MutualExclusion_protobuf_communication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MutualExclusion_protobuf_communication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MutualExclusion_protobuf_communication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewClientReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MutualExclusion_protobuf_communication_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientManipulationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MutualExclusion_protobuf_communication_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientManipulationReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MutualExclusion_protobuf_communication_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_MutualExclusion_protobuf_communication_proto_goTypes,
		DependencyIndexes: file_MutualExclusion_protobuf_communication_proto_depIdxs,
		MessageInfos:      file_MutualExclusion_protobuf_communication_proto_msgTypes,
	}.Build()
	File_MutualExclusion_protobuf_communication_proto = out.File
	file_MutualExclusion_protobuf_communication_proto_rawDesc = nil
	file_MutualExclusion_protobuf_communication_proto_goTypes = nil
	file_MutualExclusion_protobuf_communication_proto_depIdxs = nil
}
